# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3defa692b2b055c8139165ae11e3a192ec89fe2424f26b468a25013928550d23b52bb6eb50a69c20ce5792a41e21bd03e311f79e730648964fad97235a965b33

test:
  secret_key_base: 04ffc932a25e895228dad4c769c6cabcfff08c179a3b4f525b663665ebda2e94a6fa16b161e963e27b7119acfd2757807315159ba58ecfdd5b24fa40fdec900d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
